SHOW databases;
use mysql;
CREATE TABLE users (
ID INT NOT NULL AUTO_INCREMENT COMMENT '使用者ID',
ACCOUNT VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '使用者帳號',
NAME VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '使用者姓名',
PASSWORD VARCHAR(60) NOT NULL DEFAULT '0' COMMENT '使用者密碼(加密過)',
PRIMARY KEY (ID)
)
COMMENT='使用者'
COLLATE='utf8_general_ci';